title: Yijia Chen
logo: https://avatars.githubusercontent.com/u/124899185?s=400&u=105a14ceeba3d5647057ea52715d7e98e85ef7a9&v=4
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
